version: "3.9"

services:
  terapeuta-ideal-coturn-server:
    image: coturn/coturn:4.7-alpine  
    container_name: terapeuta-ideal-coturn-server
    restart: unless-stopped
    ports:
      # STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      # TLS-TURN
      - "5349:5349"
      - "5349:5349/udp"
      # CLI interface
      - "5766:5766"
      # RTP/RTCP relays (40 ports for 20 concurrent calls)
      - "49160-49200:49160-49200/udp"
    env_file:
      - .env
    volumes:
      # Bind your custom conf + persistent database & logs
      - "./turnserver.conf:/etc/coturn/turnserver.conf:ro"
      - "coturn-data:/var/lib/coturn"
      - "coturn-logs:/var/log"
      - "./letsencrypt/live/turn.terapeuta-ideal.com.br/fullchain.pem:/etc/ssl/certs/cert.pem:ro"
      - "./letsencrypt/live/turn.terapeuta-ideal.com.br/privkey.pem:/etc/ssl/private/privkey.pem:ro"
    # Use host networking if you prefer not to publish individual ports
    # network_mode: "host"
volumes:
  coturn-data:
  coturn-logs: